project/advertisement/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (AdvertisementList, AdvertisementDetail, AdvertisementCreate,
                    AdvertisementUpdate, AdvertisementDelete, ResponseList, ResponseCreate, subscribe_to_categories)

urlpatterns = [
    path('advertisements/', AdvertisementList.as_view(), name = 'advertisement_list'),
    path('advertisement/<int:pk>/', AdvertisementDetail.as_view(), name = 'advertisement_detail'),
    path('advertisement/create/', AdvertisementCreate.as_view(), name = 'advertisement_create'),
    path('advertisement/update/<int:pk>/', AdvertisementUpdate.as_view(), name = 'advertisement_update'),
    path('advertisement/delete/<int:pk>/', AdvertisementDelete.as_view(), name = 'advertisement_delete'),
    path('advertisement/create_response/<int:pk>/', ResponseCreate.as_view(), name = 'response_create'),
    path('responses/', ResponseList.as_view(), name = 'responses'),
    path('advertisement/subscription', subscribe_to_categories, name = 'subscription')
    ]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import MEDIA_URL, MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advertisement.urls')),
    path('accounts/', include("allauth.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('advertisement.urls')),
    path('accounts/', include("allauth.urls")),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/advertisement/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Author(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.username  # Возвращаем имя пользователя


class Advertisement(models.Model):
    CATEGORY = [("Tanks", "Танки"),
                ("Healers", "Хилы"),
                ("DD", "ДД"),
                ("Merchants", "Торговцы"),
                ("Guild Masters", "Гилдмастеры"),
                ("Quest Givers", "Квестгиверы"),
                ("Blacksmiths", "Кузнецы"),
                ("Tanners", "Кожевники"),
                ("Potion Makers", "Зельевары"),
                ("Spell_Masters", "Мастера заклинаний")]
    category = models.CharField(max_length=20, choices=CATEGORY)
    heading = models.CharField(max_length=200)
    content = RichTextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    time_in = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        formatted_time = self.time_in.strftime('%d %B %Y')
        return f'{self.heading}: {self.category}:{formatted_time}: {self.content}'


class Response(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
    text = models.TextField()
    answer = models.BooleanField(default=False)


    def __str__(self):
        return f'{self.user}:{self.advertisement}:{self.text}'

class Subscription(models.Model):
    CATEGORY = [("Tanks", "Танки"),
                ("Healers", "Хилы"),
                ("DD", "ДД"),
                ("Merchants", "Торговцы"),
                ("Guild Masters", "Гилдмастеры"),
                ("Quest Givers", "Квестгиверы"),
                ("Blacksmiths", "Кузнецы"),
                ("Tanners", "Кожевники"),
                ("Potion Makers", "Зельевары"),
                ("Spell_Masters", "Мастера заклинаний")]
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.CharField(max_length=20, choices=CATEGORY)

project/advertisement/forms.py
from django import forms
from .models import Advertisement, Response, Subscription


class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = [
            'category',
            'heading',
            'content',
        ]


class ResponseForm(forms.ModelForm):
    class Meta:
        model = Response
        fields = [
            'text',
        ]




class SubscriptionForm(forms.Form):
    categories = forms.MultipleChoiceField(
        choices=Subscription.CATEGORY,
        widget=forms.CheckboxSelectMultiple,  # Позволяет выбрать несколько категорий
        label="Выберите категории для подписки"
    )

project/advertisement/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from .models import Advertisement, Response, Author
from django.contrib.auth.mixins import PermissionRequiredMixin
from .forms import AdvertisementForm, ResponseForm
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, render, redirect
from .filters import ResponseFilter
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from .forms import SubscriptionForm
from .models import Subscription
from django.contrib.auth.mixins import LoginRequiredMixin


class AdvertisementList(LoginRequiredMixin, ListView):
    model = Advertisement
    ordering = 'time_in'
    template_name = 'advertisements.html'
    context_object_name = 'advertisements'
    paginate_by = 10


class AdvertisementDetail(DetailView):
    model = Advertisement
    template_name = 'advertisement.html'
    context_object_name = 'advertisement'



class AdvertisementCreate(LoginRequiredMixin, CreateView):
    form_class = AdvertisementForm
    model = Advertisement
    template_name = 'advertisement_update.html'
    success_url = reverse_lazy('advertisement_list')

    def form_valid(self, form):
        # Находим или создаем объект Author для текущего пользователя
        author, created = Author.objects.get_or_create(name=self.request.user)

        # Присваиваем автору объявление
        form.instance.author = author

        return super().form_valid(form)


class AdvertisementUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('advertisement.change_advertisement',)
    form_class = AdvertisementForm
    model = Advertisement
    template_name = 'advertisement_update.html'
    success_url = reverse_lazy('advertisement_list')




class AdvertisementDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('advertisement.change_advertisement',)
    model = Advertisement
    template_name = 'advertisement_delete.html'
    success_url = reverse_lazy('advertisement_list')


class ResponseList(ListView):
    model = Response
    template_name = 'responses.html'
    context_object_name = 'responses'
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user

        # Проверяем, связан ли пользователь с объектом Author
        try:
            author = Author.objects.get(name=user)
        except Author.DoesNotExist:
            return Response.objects.none()

        # Получаем все объявления этого автора
        advertisements = Advertisement.objects.filter(author=author)

        # Фильтруем отклики, чтобы отображать только те, которые сделаны на объявления этого автора
        queryset = Response.objects.filter(advertisement__in=advertisements)

        # Применяем фильтр, передавая только объявления текущего пользователя
        self.filterset = ResponseFilter(self.request.GET, queryset=queryset)
        self.filterset.filters['advertisement'].queryset = advertisements  # Ограничиваем объявления

        # Проверяем, есть ли выбранное объявление в фильтре
        if self.filterset.is_valid():
            # Получаем выбранное объявление из формы фильтрации
            selected_advertisement = self.filterset.form.cleaned_data.get('advertisement')

            if selected_advertisement:
                # Если выбрано конкретное объявление, фильтруем отклики по этому объявлению
                return queryset.filter(advertisement=selected_advertisement)
            else:
                # Если не выбрано конкретное объявление, возвращаем все отклики
                return queryset

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Если self.filterset не был инициализирован, сделаем это сейчас
        if not hasattr(self, 'filterset'):
            self.filterset = ResponseFilter(self.request.GET, queryset=self.get_queryset())

        context['filterset'] = self.filterset  # Передаем фильтр в контекст
        return context

    def post(self, request, *args, **kwargs):
        response_id = request.POST.get('response_id')
        action = request.POST.get('action')
        response = get_object_or_404(Response, id=response_id)

        # Получаем авторов и пользователей
        advertisement = response.advertisement
        author = advertisement.author
        author_user = author.name  # Получаем объект User через поле 'name'
        sender_user = response.user  # Пользователь, который отправил отклик

        if request.user == author_user:
            if action == 'accept':
                response.answer = True
                response.save()

                # Отправка email уведомления автору объявления
                send_mail(
                    subject=f'Ваш отклик принят',
                    message=f'Здравствуйте, {sender_user.username}!\n\n'
                            f'Ваш отклик на объявление "{advertisement.heading}" был принят автором.',
                    from_email='wr9va@yandex.com',
                    recipient_list=[sender_user.email],
                    fail_silently=False,
                )
            elif action == 'delete':
                response.delete()

        return redirect('responses')


class ResponseCreate(LoginRequiredMixin, CreateView):
    model = Response
    form_class = ResponseForm
    template_name = 'response_create.html'
    success_url = reverse_lazy('advertisement_list')

    def form_valid(self, form):
        # Получаем идентификатор объявления из URL
        advertisement_id = self.kwargs.get('pk')

        # Проверяем, что идентификатор объявления существует
        if advertisement_id:
            # Получаем объект Advertisement или вызываем ошибку 404, если не найден
            advertisement = get_object_or_404(Advertisement, id=advertisement_id)
            form.instance.advertisement = advertisement  # Устанавливаем поле advertisement
        else:
            # Обработка ошибки, если идентификатор объявления не передан
            return self.form_invalid(form)

        form.instance.user = self.request.user  # Устанавливаем текущего пользователя

        # Сохраняем форму и получаем объект Response
        response = super().form_valid(form)

        # Отправка email уведомления владельцу объявления
        author = form.instance.advertisement.author
        author_user = author.name  # Получаем объект User через поле 'name'

        send_mail(
            subject=f'У вас новый отклик на объявление "{form.instance.advertisement.heading}"',
            message=f'Здравствуйте, {author_user.username}!\n\n'
                    f'Вы получили новый отклик от пользователя {self.request.user.username}. '
                    f'Вы можете просмотреть его на сайте.',
            from_email='wr9va@yandex.com',
            recipient_list=[author_user.email],  # Email владельца объявления
            fail_silently=False,
        )

        return response




@login_required
def subscribe_to_categories(request):
    if request.method == 'POST':
        form = SubscriptionForm(request.POST)
        if form.is_valid():
            categories = form.cleaned_data['categories']
            for category in categories:
                Subscription.objects.get_or_create(user=request.user, category=category)
            return redirect('advertisement_list')
    else:
        form = SubscriptionForm()

    return render(request, 'subscription.html', {'form': form})

project/templates/advertisement.html
{% extends 'fpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Advertisement
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ advertisement }}</h1>
{% endblock content %}

project/templates/advertisement_delete.html
{% extends 'fpages/default.html' %}

{% block content %}
<h1>Удаление объявлния</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.heading }}"?</p>
    <input type="submit" value="DELETE" />
</form>
{% endblock content %}

project/templates/advertisement_update.html
{% extends 'fpages/default.html' %}

{% block content %}
<h1>Объявление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/advertisements.html
{% extends 'fpages/default.html' %}

{% block content %}
   <h1>Все объявления</h1>
   <h3>{{ advertisements|length }}</h3>

   <!-- Ссылки на создание объявления и просмотр откликов без передачи advertisement.id -->
   <a href="{% url 'account_logout' %}" class="btn">Выйти из аккаунта</a>
   <a href="{% url 'advertisement_create' %}" class="btn">Создать объявление</a>
   <a href="{% url 'responses' %}" class="btn">Отклики</a>
   <a href="{% url 'subscription' %}" class="btn">Подписки</a>

   <hr>
   {% if advertisements %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Категория</td>
               <td>Дата публикации</td>
               <td>Содержание</td>
           </tr>

           {% for advertisement in advertisements %}
           <tr>
               <td>{{ advertisement.heading }}</td>
               <td>{{ advertisement.category }}</td>
               <td>{{ advertisement.time_in }}</td>
               <td>{{ advertisement.content|truncatewords:20 }}</td>
               <td>
                    {% if perms.advertisement.change_advertisement or advertisement.author == user %}
                    <a href="{% url 'advertisement_update' advertisement.id %}">Изменить</a>
                    {% endif %}
               </td>
               <td>
                    {% if perms.advertisement.delete_advertisement or advertisement.author == user %}
                    <a href="{% url 'advertisement_delete' advertisement.id %}">Удалить</a>
                    {% endif %}
               </td>
               <td>
                    <a href="{% url 'response_create' advertisement.id %}">Создать отзыв</a>
               </td>
           </tr>
           {% endfor %}
       </table>
   {% else %}
       <h2>Объявлений нет!</h2>
   {% endif %}

   {# Пагинация #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

project/templates/response_create.html
{% extends 'fpages/default.html' %}

{% block content %}
<h1>Отзыв</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/responses.html
{% extends 'fpages/default.html' %}

{% block content %}
   <h1>Отклики</h1>
   <h3>{{ responses|length }} откликов</h3>

   <a href="{% url 'advertisement_list' %}" class="btn">Объявлния</a>

   <form method="get">
       {{ filterset.form.as_p }}
       <button type="submit">Фильтровать</button>
   </form>

   <hr>
   {% if responses %}
       <table>
           <tr>
               <th>Объявление</th>
               <th>Содержание</th>
               <th>Действия</th>
           </tr>

           {% for response in responses %}
           <tr>
               <td>{{ response.advertisement }}</td>
               <td>{{ response.text }}</td>
               <td>
                    {% if not response.answer %}
                        <!-- Кнопка для принятия отклика -->
                        <form action="{% url 'responses' %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="response_id" value="{{ response.id }}">
                            <input type="hidden" name="action" value="accept">
                            <button type="submit">Принять</button>
                        </form>
                        <!-- Кнопка для удаления отклика -->
                        <form action="{% url 'responses' %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="response_id" value="{{ response.id }}">
                            <input type="hidden" name="action" value="delete">
                            <button type="submit">Удалить</button>
                        </form>
                    {% else %}
                        <span>Принято</span>
                    {% endif %}
               </td>
           </tr>

           {% endfor %}

       </table>
   {% else %}
       <h2>Откликов нет!</h2>
   {% endif %}

   <!-- Добавляем пагинацию на страницу -->
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if page_obj.paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

project/templates/subscription.html
{% extends 'fpages/default.html' %}

{% block content %}
  <h2>Подписаться на категории</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Подписаться</button>
<<<<<<< HEAD

=======
>>>>>>> origin/main
  </form>
{% endblock %}